services:
  postgres:
    image: postgres:17.5-alpine3.22
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=url_shortener
    ports:
      - "5432:5432"
    volumes:
    - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:123456@postgres:5432/url_shortener?sslmode=disable
    depends_on:
      - postgres