// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Url struct {
	ID          int32     `json:"id"`
	OriginalUrl string    `json:"original_url"`
	TimeCreated time.Time `json:"time_created"`
}

type Visitor struct {
	Ip          string    `json:"ip"`
	UrlID       int32     `json:"url_id"`
	TimeVisited time.Time `json:"time_visited"`
}
