// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visitor.sql

package db

import (
	"context"
)

const createVisitor = `-- name: CreateVisitor :one
INSERT INTO visitor(ip, url_id)
VALUES ($1, $2)
RETURNING ip, url_id, time_visited
`

type CreateVisitorParams struct {
	Ip    string `json:"ip"`
	UrlID int32  `json:"url_id"`
}

func (q *Queries) CreateVisitor(ctx context.Context, arg CreateVisitorParams) (Visitor, error) {
	row := q.db.QueryRowContext(ctx, createVisitor, arg.Ip, arg.UrlID)
	var i Visitor
	err := row.Scan(&i.Ip, &i.UrlID, &i.TimeVisited)
	return i, err
}

const listVisitor = `-- name: ListVisitor :many
SELECT ip, url_id, time_visited FROM visitor 
WHERE url_id = $1
OFFSET $2
LIMIT $3
`

type ListVisitorParams struct {
	UrlID  int32 `json:"url_id"`
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListVisitor(ctx context.Context, arg ListVisitorParams) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, listVisitor, arg.UrlID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Visitor{}
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(&i.Ip, &i.UrlID, &i.TimeVisited); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
